#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-Ryacas
Version  : 1.1.3.1
Release  : 3
URL      : https://cran.r-project.org/src/contrib/Ryacas_1.1.3.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/Ryacas_1.1.3.1.tar.gz
Summary  : R Interface to the 'Yacas' Computer Algebra System
Group    : Development/Tools
License  : LGPL-2.1
Requires: R-Ryacas-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-magrittr
BuildRequires : R-Rcpp
BuildRequires : R-magrittr
BuildRequires : buildreq-R

%description
No detailed description available

%package lib
Summary: lib components for the R-Ryacas package.
Group: Libraries

%description lib
lib components for the R-Ryacas package.


%prep
%setup -q -c -n Ryacas
cd %{_builddir}/Ryacas

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1657759225

%install
export SOURCE_DATE_EPOCH=1657759225
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library Ryacas
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library Ryacas
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library Ryacas
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc Ryacas || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/Ryacas/CITATION
/usr/lib64/R/library/Ryacas/DESCRIPTION
/usr/lib64/R/library/Ryacas/INDEX
/usr/lib64/R/library/Ryacas/Meta/Rd.rds
/usr/lib64/R/library/Ryacas/Meta/demo.rds
/usr/lib64/R/library/Ryacas/Meta/features.rds
/usr/lib64/R/library/Ryacas/Meta/hsearch.rds
/usr/lib64/R/library/Ryacas/Meta/links.rds
/usr/lib64/R/library/Ryacas/Meta/nsInfo.rds
/usr/lib64/R/library/Ryacas/Meta/package.rds
/usr/lib64/R/library/Ryacas/Meta/vignette.rds
/usr/lib64/R/library/Ryacas/NAMESPACE
/usr/lib64/R/library/Ryacas/NEWS
/usr/lib64/R/library/Ryacas/R/Ryacas
/usr/lib64/R/library/Ryacas/R/Ryacas.rdb
/usr/lib64/R/library/Ryacas/R/Ryacas.rdx
/usr/lib64/R/library/Ryacas/THANKS
/usr/lib64/R/library/Ryacas/WISHLIST
/usr/lib64/R/library/Ryacas/demo/Ryacas-Expr.R
/usr/lib64/R/library/Ryacas/demo/Ryacas-Function.R
/usr/lib64/R/library/Ryacas/demo/Ryacas-PrettyPrinter.R
/usr/lib64/R/library/Ryacas/demo/Ryacas-Sym.R
/usr/lib64/R/library/Ryacas/demo/Ryacas-gui.R
/usr/lib64/R/library/Ryacas/demo/Ryacas.R
/usr/lib64/R/library/Ryacas/doc/arbitrary-precision.R
/usr/lib64/R/library/Ryacas/doc/arbitrary-precision.Rmd
/usr/lib64/R/library/Ryacas/doc/arbitrary-precision.html
/usr/lib64/R/library/Ryacas/doc/getting-started.R
/usr/lib64/R/library/Ryacas/doc/getting-started.Rmd
/usr/lib64/R/library/Ryacas/doc/getting-started.html
/usr/lib64/R/library/Ryacas/doc/high-level.R
/usr/lib64/R/library/Ryacas/doc/high-level.Rmd
/usr/lib64/R/library/Ryacas/doc/high-level.html
/usr/lib64/R/library/Ryacas/doc/index.html
/usr/lib64/R/library/Ryacas/doc/latent-variable-model.R
/usr/lib64/R/library/Ryacas/doc/latent-variable-model.Rmd
/usr/lib64/R/library/Ryacas/doc/latent-variable-model.html
/usr/lib64/R/library/Ryacas/doc/low-level.R
/usr/lib64/R/library/Ryacas/doc/low-level.Rmd
/usr/lib64/R/library/Ryacas/doc/low-level.html
/usr/lib64/R/library/Ryacas/doc/ssm-matrix.R
/usr/lib64/R/library/Ryacas/doc/ssm-matrix.Rmd
/usr/lib64/R/library/Ryacas/doc/ssm-matrix.html
/usr/lib64/R/library/Ryacas/doc/yacas-rules.R
/usr/lib64/R/library/Ryacas/doc/yacas-rules.Rmd
/usr/lib64/R/library/Ryacas/doc/yacas-rules.html
/usr/lib64/R/library/Ryacas/help/AnIndex
/usr/lib64/R/library/Ryacas/help/Ryacas.rdb
/usr/lib64/R/library/Ryacas/help/Ryacas.rdx
/usr/lib64/R/library/Ryacas/help/aliases.rds
/usr/lib64/R/library/Ryacas/help/paths.rds
/usr/lib64/R/library/Ryacas/html/00Index.html
/usr/lib64/R/library/Ryacas/html/R.css
/usr/lib64/R/library/Ryacas/tests/test-all.R
/usr/lib64/R/library/Ryacas/tests/testthat/test-bugs.R
/usr/lib64/R/library/Ryacas/tests/testthat/test-ryacas-init.R
/usr/lib64/R/library/Ryacas/tests/testthat/test-smoke.R
/usr/lib64/R/library/Ryacas/tests/testthat/test-symbol.R
/usr/lib64/R/library/Ryacas/yacas-custom/ryacasinit.ys
/usr/lib64/R/library/Ryacas/yacas/array.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/array.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/assoc.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/assoc.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/base.rep/math.ys
/usr/lib64/R/library/Ryacas/yacas/base.rep/math.ys.def
/usr/lib64/R/library/Ryacas/yacas/c_form.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/c_form.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/calendar.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/calendar.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/complex.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/complex.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/complex.rep/om.ys
/usr/lib64/R/library/Ryacas/yacas/constants.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/constants.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/constants.rep/om.ys
/usr/lib64/R/library/Ryacas/yacas/controlflow.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/controlflow.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/cse.rep/cse.ys
/usr/lib64/R/library/Ryacas/yacas/cse.rep/cse.ys.def
/usr/lib64/R/library/Ryacas/yacas/debug.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/debug.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/deffunc.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/deffunc.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/deriv.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/deriv.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/example.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/example.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/examples/ABIN.ys
/usr/lib64/R/library/Ryacas/yacas/examples/MinimumSpanningTree.ys
/usr/lib64/R/library/Ryacas/yacas/examples/benchbuild.ys
/usr/lib64/R/library/Ryacas/yacas/examples/benchmark.ys
/usr/lib64/R/library/Ryacas/yacas/examples/benchmark2.ys
/usr/lib64/R/library/Ryacas/yacas/examples/findsum.ys
/usr/lib64/R/library/Ryacas/yacas/examples/goldbach.ys
/usr/lib64/R/library/Ryacas/yacas/examples/pi.ys
/usr/lib64/R/library/Ryacas/yacas/examples/queens.ys
/usr/lib64/R/library/Ryacas/yacas/examples/series.ys
/usr/lib64/R/library/Ryacas/yacas/examples/wordproblems.ys
/usr/lib64/R/library/Ryacas/yacas/factors.rep/binaryfactors.ys
/usr/lib64/R/library/Ryacas/yacas/factors.rep/binaryfactors.ys.def
/usr/lib64/R/library/Ryacas/yacas/factors.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/factors.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/functional.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/functional.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/functional.rep/om.ys
/usr/lib64/R/library/Ryacas/yacas/graph.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/graph.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/html.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/html.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/integrate.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/integrate.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/integrate.rep/om.ys
/usr/lib64/R/library/Ryacas/yacas/io.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/io.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/io.rep/defaultprint.ys
/usr/lib64/R/library/Ryacas/yacas/io.rep/defaultprint.ys.def
/usr/lib64/R/library/Ryacas/yacas/io.rep/errors.ys
/usr/lib64/R/library/Ryacas/yacas/io.rep/formula.ys
/usr/lib64/R/library/Ryacas/yacas/io.rep/print.ys
/usr/lib64/R/library/Ryacas/yacas/limit.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/limit.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/limit.rep/om.ys
/usr/lib64/R/library/Ryacas/yacas/linalg.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/linalg.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/lists.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/lists.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/lists.rep/scopestack.ys
/usr/lib64/R/library/Ryacas/yacas/lists.rep/scopestack.ys.def
/usr/lib64/R/library/Ryacas/yacas/localrules.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/localrules.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/logic.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/logic.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/logic.rep/om.ys
/usr/lib64/R/library/Ryacas/yacas/multivar.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/multivar.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/multivar.rep/makemulti.ys
/usr/lib64/R/library/Ryacas/yacas/multivar.rep/sparsenomial.ys
/usr/lib64/R/library/Ryacas/yacas/multivar.rep/sparsetree.ys
/usr/lib64/R/library/Ryacas/yacas/multivar.rep/sparsetree.ys.def
/usr/lib64/R/library/Ryacas/yacas/newly.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/newly.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/nintegrate.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/nintegrate.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/numbers.rep/GaussianIntegers.ys
/usr/lib64/R/library/Ryacas/yacas/numbers.rep/GaussianIntegers.ys.def
/usr/lib64/R/library/Ryacas/yacas/numbers.rep/NumberTheory.ys
/usr/lib64/R/library/Ryacas/yacas/numbers.rep/NumberTheory.ys.def
/usr/lib64/R/library/Ryacas/yacas/numbers.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/numbers.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/numbers.rep/nthroot.ys
/usr/lib64/R/library/Ryacas/yacas/numbers.rep/nthroot.ys.def
/usr/lib64/R/library/Ryacas/yacas/numbers.rep/om.ys
/usr/lib64/R/library/Ryacas/yacas/odesolver.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/odesolver.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/openmath.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/openmath.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/orthopoly.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/orthopoly.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/packages.ys
/usr/lib64/R/library/Ryacas/yacas/padic.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/padic.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/patterns.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/patterns.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/physics.rep/quantum/clebsch-gordan.ys
/usr/lib64/R/library/Ryacas/yacas/physics.rep/quantum/clebsch-gordan.ys.def
/usr/lib64/R/library/Ryacas/yacas/plots.rep/backends-2d.ys
/usr/lib64/R/library/Ryacas/yacas/plots.rep/backends-3d.ys
/usr/lib64/R/library/Ryacas/yacas/plots.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/plots.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/plots.rep/plot2d.ys
/usr/lib64/R/library/Ryacas/yacas/plots.rep/plot2d.ys.def
/usr/lib64/R/library/Ryacas/yacas/plots.rep/plot3d.ys
/usr/lib64/R/library/Ryacas/yacas/plots.rep/plot3d.ys.def
/usr/lib64/R/library/Ryacas/yacas/predicates.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/predicates.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/probability.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/probability.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/products.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/products.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/pslq.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/pslq.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/r_form.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/r_form.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/rabinmiller.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/rabinmiller.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/radsimp.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/radsimp.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/random.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/random.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/rational.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/rational.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/simplify.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/simplify.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/simplify.rep/factorial.ys
/usr/lib64/R/library/Ryacas/yacas/simplify.rep/factorial.ys.def
/usr/lib64/R/library/Ryacas/yacas/solve.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/solve.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/specfunc.rep/bernou.ys
/usr/lib64/R/library/Ryacas/yacas/specfunc.rep/bernou.ys.def
/usr/lib64/R/library/Ryacas/yacas/specfunc.rep/bessel.ys
/usr/lib64/R/library/Ryacas/yacas/specfunc.rep/bessel.ys.def
/usr/lib64/R/library/Ryacas/yacas/specfunc.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/specfunc.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/specfunc.rep/gamma.ys
/usr/lib64/R/library/Ryacas/yacas/specfunc.rep/gamma.ys.def
/usr/lib64/R/library/Ryacas/yacas/specfunc.rep/gammaconst.ys
/usr/lib64/R/library/Ryacas/yacas/specfunc.rep/gammaconst.ys.def
/usr/lib64/R/library/Ryacas/yacas/specfunc.rep/om.ys
/usr/lib64/R/library/Ryacas/yacas/specfunc.rep/zeta.ys
/usr/lib64/R/library/Ryacas/yacas/specfunc.rep/zeta.ys.def
/usr/lib64/R/library/Ryacas/yacas/standard.ys
/usr/lib64/R/library/Ryacas/yacas/standard.ys.def
/usr/lib64/R/library/Ryacas/yacas/statistics.rep/distributions.ys
/usr/lib64/R/library/Ryacas/yacas/statistics.rep/distributions.ys.def
/usr/lib64/R/library/Ryacas/yacas/statistics.rep/hypothesystest.ys
/usr/lib64/R/library/Ryacas/yacas/statistics.rep/hypothesystest.ys.def
/usr/lib64/R/library/Ryacas/yacas/statistics.rep/incompletegamma.ys
/usr/lib64/R/library/Ryacas/yacas/statistics.rep/incompletegamma.ys.def
/usr/lib64/R/library/Ryacas/yacas/statistics.rep/randomtest.ys
/usr/lib64/R/library/Ryacas/yacas/statistics.rep/regression.ys
/usr/lib64/R/library/Ryacas/yacas/statistics.rep/regression.ys.def
/usr/lib64/R/library/Ryacas/yacas/statistics.rep/statistics.ys
/usr/lib64/R/library/Ryacas/yacas/statistics.rep/statistics.ys.def
/usr/lib64/R/library/Ryacas/yacas/stats.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/stats.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/stdarith.ys
/usr/lib64/R/library/Ryacas/yacas/stdarith.ys.def
/usr/lib64/R/library/Ryacas/yacas/stdfuncs.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/stdfuncs.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/stdfuncs.rep/elemfuncs.ys
/usr/lib64/R/library/Ryacas/yacas/stdfuncs.rep/elemfuncs.ys.def
/usr/lib64/R/library/Ryacas/yacas/stdfuncs.rep/numerical.ys
/usr/lib64/R/library/Ryacas/yacas/stdfuncs.rep/numerical.ys.def
/usr/lib64/R/library/Ryacas/yacas/stdfuncs.rep/nummethods.ys
/usr/lib64/R/library/Ryacas/yacas/stdfuncs.rep/nummethods.ys.def
/usr/lib64/R/library/Ryacas/yacas/stdfuncs.rep/om.ys
/usr/lib64/R/library/Ryacas/yacas/stdopers.ys
/usr/lib64/R/library/Ryacas/yacas/stubs.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/stubs.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/stubs.rep/om.ys
/usr/lib64/R/library/Ryacas/yacas/substitute.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/substitute.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/sums.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/sums.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/sums.rep/om.ys
/usr/lib64/R/library/Ryacas/yacas/sums.rep/taylor.ys
/usr/lib64/R/library/Ryacas/yacas/sums.rep/taylor.ys.def
/usr/lib64/R/library/Ryacas/yacas/sums.rep/taylor3.ys
/usr/lib64/R/library/Ryacas/yacas/sums.rep/taylor3.ys.def
/usr/lib64/R/library/Ryacas/yacas/tensor.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/tensor.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/testers.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/testers.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/texform.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/texform.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/transforms.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/transforms.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/trigsimp.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/trigsimp.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/univar.rep/Cyclotomic.ys
/usr/lib64/R/library/Ryacas/yacas/univar.rep/Cyclotomic.ys.def
/usr/lib64/R/library/Ryacas/yacas/univar.rep/code.ys
/usr/lib64/R/library/Ryacas/yacas/univar.rep/code.ys.def
/usr/lib64/R/library/Ryacas/yacas/univar.rep/sparse.ys
/usr/lib64/R/library/Ryacas/yacas/univar.rep/sparse.ys.def
/usr/lib64/R/library/Ryacas/yacas/univar.rep/sturm.ys
/usr/lib64/R/library/Ryacas/yacas/univar.rep/sturm.ys.def
/usr/lib64/R/library/Ryacas/yacas/yacasinit.ys

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/Ryacas/libs/Ryacas.so
/usr/lib64/R/library/Ryacas/libs/Ryacas.so.avx2
/usr/lib64/R/library/Ryacas/libs/Ryacas.so.avx512
